model:
  # paths
  llama_path: "meta-llama/Llama-3.2-1B-Instruct"
  whisper_path: "openai/whisper-large-v3"
  
  # beats나 ced 둘 중 하나는 비워둬야함
  #beats_path: "/data/data_storage/model_weight/BEATs_iter3_plus_AS2M_finetuned_on_AS2M_cpt2.pt" # 다운로드 받은 BEATs 파일 경로
  ced_path: "ced_small" 
  ckpt: "" # stage2 마친 모델 .ckpt or .pth

  only_preprocessor: False
  low_resource: True
  freeze_whisper: True
  freeze_beats: True

  # window-level Q-Former
  use_speech_Qformer: True
  freeze_speech_QFormer: False
  window_level_Qformer: True
  num_speech_query_token: 1
  second_per_window: 0.333333
  second_stride: 0.333333

  speech_llama_proj_model: ""
  freeze_speech_llama_proj: False

  # LoRA
  lora: True
  lora_rank: 8
  lora_alpha: 32
  lora_dropout: 0.1

  multi_prompt: True
  prompt_template: "USER: {}\nASSISTANT:"
  prompt_path: "/e/Github/BoostClass AI Tech/Final Project/level4-nlp-finalproject-hackathon-nlp-07-lv3/src/prompts/train_prompt.json"
  test_prompt_path: "/e/Github/BoostClass AI Tech/Final Project/level4-nlp-finalproject-hackathon-nlp-07-lv3/src/prompts/test_prompt.json"
  max_txt_len: 300
  end_sym: "<|end_of_text|>" # 사용하는 LLM에 맞춰 변경

generate:
  max_new_tokens: 200
  num_beams: 4
  do_sample: False
  min_length: 1
  temperature: 1.0
  top_p: 0.9
  repetition_penalty: 1.0
  length_penalty: 1.0
  end_sym: "<|end_of_text|>"

datasets:
  prefix: "/e/Github/BoostClass AI Tech/Final Project/level4-nlp-finalproject-hackathon-nlp-07-lv3/src/data/"
  test_ann_path_asr: "test_asr.json"
  test_ann_path_aac: "test_aac.json"

run:
  batch_size_eval: 8
  num_workers: 4
  device: "cuda:0"
