model:
  # paths
  llama_path: "meta-llama/Llama-3.2-3B-Instruct"
  whisper_path: "openai/whisper-large-v2"
  beats_path: "" # 다운로드 받은 BEATs 파일 경로

  token: "" # 허깅페이스 토큰
  only_preprocessor: False

  ckpt: "" # stage2 마친 모델 .ckpt or .pth

  freeze_whisper: True
  freeze_beats: True

  # window-level Q-Former
  use_speech_Qformer: True
  freeze_speech_QFormer: False
  window_level_Qformer: True
  num_speech_query_token: 1
  second_per_window: 0.333333
  second_stride: 0.333333

  speech_llama_proj_model: ""
  freeze_speech_llama_proj: False

  # LoRA
  lora: True
  lora_rank: 8
  lora_alpha: 32
  lora_dropout: 0.1

  multi_prompt: True
  prompt_template: "USER: {}\nASSISTANT:"
  prompt_path: "./prompts/train_prompt.json"
  test_prompt_path: "./prompts/test_prompt.json"
  max_txt_len: 300
<<<<<<< HEAD
  end_sym: "<|eot_id|>"   # 사용하는 LLM에 맞춰 변경
=======
  end_sym: "<|eot_id|>"
>>>>>>> 4eb82f6 (Title: add evaluation code)

generate:
  max_new_tokens: 200
  num_beams: 4
  do_sample: True
  min_length: 1
  temperature: 1.0
  top_p: 0.9
  repetition_penalty: 1.0
  length_penalty: 1.0
<<<<<<< HEAD
  end_sym: "<|eot_id|>"  # 사용하는 LLM에 맞춰 변경
=======
  end_sym: "<|end_of_text|>"
>>>>>>> 4eb82f6 (Title: add evaluation code)

datasets:
  prefix: "./data"
  test_ann_path: "./data/test_asr.json" # test_asr.json or test_acc.json
  whisper_path: "openai/whisper-large-v2"

run:
  batch_size_eval: 8
<<<<<<< HEAD
  num_workers: 4
  device: "cuda"
=======
  num_workers: 8
  device: "cuda"
>>>>>>> 4eb82f6 (Title: add evaluation code)
